### ISSUE TITLE
/!\ MERGE LYRICS SERVEUR ET LOCAL /!\

### ISSUE THREAD

**Issue by fabrice126** [fabrice126/wasabi_project#106]
Michel ajoute des lyrics pour les musiques populaires: (led zeppelin notamment ), pour ne pas perdre les nouvelles lyrics lors de la ré-importation de la base sur le serveur : faire un merge

**Comment by micbuffa** [comment]
Ok, attends mon feu vert, je n'ai pas fini

Le lun. 4 juil. 2016 à 14:48, fabrice126 notifications@github.com a
écrit :

**Comment by fabrice126** [comment]
Ok, je suis entrain de regarder ton code de MT5 pour le passer en composant + ES6
