### ISSUE TITLE
Trouver les chansons ayant marqué l'histoire

### ISSUE THREAD

**Issue by fabrice126** [fabrice126/wasabi_project#112]
Pour savoir si une chanson a marqué l'histoire nous pouvons regarder dans notre BDD la propriété subject ex: 
- /award/i -> 6108 occurrences
- /number-one/i -> 24941 occurrences
- /best/i -> 2213 occurrences
- /Hall_of_fame/i -> 3732 occurrences
- /diamond/i -> 604  occurrences
- /platinum/i -> 1910 occurrences
- /gold/i -> 3653 occurrences
- /hot_100/i -> 6827 occurrences

**Comment by micbuffa** [comment]
Ok, commence avec ça et on affinera. J'aimerais bien aussi dans la GUI un
bouton pour le dire manuellement... et mettre éventuellement un champ de
texte pour entrer quelques phrases pour dire pourquoi...

Le lun. 11 juil. 2016 à 14:02, fabrice126 notifications@github.com a
écrit :

**Comment by micbuffa** [comment]
Y'a des chansons qui ont marqué l'histoire et qui n'ont eu aucun succès
public, ou des disques... ex: le velvet underground, suicide, les
stooges... Ils ont très peu vendu mais plein plein de groupes se sont
créés, influencés par eux, par la suite. Ou encore, tu as une chanson
célèbre car on entend une "cruche electrique" (Psychotic Reaction du 13th
floor Elevator), qui n'a pas eu trop de succes non plus, ou la première
chanson avec du feedback, etc...

**Comment by fabrice126** [comment]
Mettre des commentaires sur les musiques c'est ça ? Ou un autre système ? 
Concernant le bouton j'ai compris, je vais mettre une petite étoile cliquable qui devient jaune comme pour les favoris de chrome.

**Comment by micbuffa** [comment]
Oui étoile et aussi un petit champ optionnel pour indiqué au cas où
pourquoi c'est exceptionnel, en français et en anglais.
