### ISSUE TITLE
Certaines musiques ayant été interprétés par plusieurs artistes différents ont la même URL Wikipédia

### ISSUE THREAD

**Issue by fabrice126** [fabrice126/wasabi_project#113]
Certaines musiques ayant été interprétés par plusieurs artistes différents ont la même URL Wikipédia ce qui signifie que si l'artiste X à chanté Thriller de Michael jackson ses propriétés issues du RDF seront celles de Thriller de Michael Jackson, ex: subject, award, producer, abstract etc ...

**Comment by micbuffa** [comment]
Oui c'est parceque on est partis des paroles

**Comment by micbuffa** [comment]
Après que la chanson est identifiée aussi par le disque et l'artiste et le
fait que le disque est un live  un Best of etc. Tu as aussi des disques
fais par plein d'artistes, ce sont des compilations... Il faudra les
distinguer   ... Best of dance 2009, tu l'accrochage à quel artiste ?

**Comment by fabrice126** [comment]
Il ne semble pas y avoir de compilation sur lyrics wikia donc pas de Best of dance 2009 etc.

**Comment by micbuffa** [comment]
Hmmm mais ça peut arriver non qu'on ai un disque avec plusieurs artistes ?
Pour le moment en effet, en partant de lyrics wikia... Hmmm tu es sur ? Je
vais vérifier !

**Comment by fabrice126** [comment]
Oui il peut y avoir des albums ayant plusieurs artistes (c'est souvent le
cas pour les dj) mais il n'y a aucune compilation
