### ISSUE TITLE
Geolocation page-404.html chrome security policy

### ISSUE THREAD

**Issue by fabrice126** [fabrice126/wasabi_project#69]
"Google recently announced a security policy change that will impact future versions of the Chrome browser. Chrome is already warning that support to powerful features on insecure origins (HTTP) is deprecated, and according to recent announcements the removal will take place soon.

The initial features that will be removed on insecure origins will be:

Geolocation (getCurrentPosition() and watchPosition())

if your web site or app is currently using any powerful feature above, please immediately consider switching all your traffic to HTTPS only."

**Comment by micbuffa** [comment]
Ok, merci.
